from typing import List, Iterable

class Vector:
    def __init__(self, value: int | Iterable) -> None: ...

    def size(self) -> int: ...

    def dot(self, other: "Vector") -> float: ...

    def magnitude(self) -> float: ...

    def normalize(self) -> "Vector": ...

    def cross(self, other: "Vector") -> "Vector": ...

    def __getitem__(self, index: int) -> float: ...

    def __setitem__(self, index: int, value: float) -> None: ...

    def __add__(self, other: "Vector") -> "Vector": ...

    def __sub__(self, other: "Vector") -> "Vector": ...

    def __mul__(self, other: "Vector | float") -> "Vector": ...

    def __truediv__(self, other: "Vector | float") -> "Vector": ...
    
class Matrix:
    def __init__(self, rows: int, cols: int, value: Iterable) -> None: ...

    def getRows(self) -> int: ...

    def getCols(self) -> int: ...

    def transpose(self) -> "Matrix": ...

    def determinant(self) -> float: ...

    def inverse(self) -> "Matrix": ...

    def matmul(self, other: "Matrix") -> "Matrix": ...